"Facade for tab rendering layer."

from views.universal_dashboard import render_universal_dashboard
from views.unified_overview_tab import render_unified_overview_tab
from views.universal_key_insights_tab import render_universal_key_insights_tab
from views.chat_history_tab import render_chat_history_tab
from views.statistics_tab import render_statistics_tab
from views.timeline_tab import render_timeline_tab
from views.comparative_tab import render_comparative_tab
from views.prompt_analysis_tab import render_prompt_analysis_tab
from views.universal_required_stats_tab import render_universal_required_stats_tab

